# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bot Framework
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 The Microsoft Bot Framework provides just what you need to build and connect intelligent bots that interact naturally wherever your users are talking, from text/sms to Skype, Slack, Office 365 mail and other popular services.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
include: [_*.html]
exclude: [bot-connector-rest-api-reference.md,dev-portal-channel-configuration.md,build-docs.cmd,/sandbox/qnawizard-howto.md,/sandbox/qnawizard-overview.md,/Connector/Direct Line.md,README.md,search_data.json]
lsi: false

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
